# Generated by Django 5.1 on 2024-08-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="game_id",
            field=models.IntegerField(null=True),
        ),
    ]
