# Generated by Django 5.1 on 2024-08-21 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Match',
        ),
    ]
