# Generated by Django 4.2.15 on 2024-09-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='online_check',
            field=models.BooleanField(default=True),
        ),
    ]
