version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - psql-volume:/var/lib/postgresql/data
    networks:
      - inception_network

  django:
    build: ./ft_transcendence
    container_name: my_django
    depends_on:
      - postgres
    volumes:
      - ./ft_transcendence:/app
    networks:
      - inception_network

  nginx:
    build: ./nginx
    container_name: my_nginx
    depends_on:
      - django
    ports:
      - "443:443"
    # volumes:
    #   - ./nginx/conf.d:/etc/nginx/conf.d
    #   - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - inception_network
networks:
  inception_network:
    driver: bridge
    name: inception_network

volumes:
  psql-volume:
    driver_opts:
      o: bind
      type: none
      device: ~/data/psql
