version: '3.8'

services:
  postgres:
    build: ./postgreSQL
    container_name: postgres
    env_file:
      .env_postgres
    networks:
      - inception_network

  redis:
    build: ./redis
    container_name: my_redis
    networks:
      - inception_network

  vault:
    build: ./vault
    container_name: vault
    depends_on:
      - postgres
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    volumes:
      - token-volume:/vault/token-volume/
    env_file:
      - .env
      - .env_postgres
    networks:
      - inception_network

  django:
    build: ./ft_transcendence
    container_name: my_django
    depends_on:
      - postgres
      - redis
    volumes:
      - token-volume:/vault/token-volume/
      - static_volume:/app/staticfiles
    networks:
      - inception_network

  nginx:
    build: ./nginx
    container_name: my_nginx
    depends_on:
      - django
    ports:
      - "443:443"
    networks:
      - inception_network
    volumes:
      - static_volume:/app/staticfiles


networks:
  inception_network:
    driver: bridge
    name: inception_network

volumes:
  token-volume:
  static_volume: