version: '3.8'

services:
  postgres:
    build: ./postgreSQL
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword1
      POSTGRES_DB: mydatabase
    volumes:
      - psql-volume:/var/lib/postgresql/data
    networks:
      - inception_network

  redis:
    build: ./redis
    container_name: my_redis
    networks:
      - inception_network

  vault:
    build: ./vault
    container_name: vault
    depends_on:
      - postgres
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    volumes:
      - token-volume:/vault/token-volume/
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword1
      POSTGRES_DB: mydatabase
    networks:
      - inception_network

  django:
    build: ./ft_transcendence
    container_name: my_django
    depends_on:
      - postgres
      - redis
    volumes:
      - ./ft_transcendence:/app
      - token-volume:/vault/token-volume/
      - ~/data/localip/:/localip
      - ./.domain_name.txt:/domain_name.txt
    env_file:
      .env
    networks:
      - inception_network

  nginx:
    build: ./nginx
    container_name: my_nginx
    depends_on:
      - django
    ports:
      - "443:443"
    networks:
      - inception_network


networks:
  inception_network:
    driver: bridge
    name: inception_network

volumes:
  token-volume:

  psql-volume:
    driver_opts:
      o: bind
      type: none
      device: ~/data/psql
  vault-volume:
    driver_opts:
      o: bind
      type: none
      device: ~/data/vault

