FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install dependencies
RUN pip install --upgrade pip && mkdir -p /localip
RUN pip install psycopg2 --no-cache-dir -r requirements.txt
RUN python -m pip install -Iv channels==3.0.5
RUN pip install channels_redis==3.3.1 redis hvac
RUN pip install web3
RUN pip install djangorestframework
# Copy the rest of the application code
COPY . .

# Set environment variable to disable output buffering
ENV PYTHONUNBUFFERED=1

# Copy the entrypoint script into the container
COPY entrypoint.sh /app/entrypoint.sh

# Make the entrypoint script executable
RUN chmod +x /app/entrypoint.sh

# Expose port 8000
EXPOSE 8000

# Use the entrypoint script
ENTRYPOINT ["/app/entrypoint.sh"]
