# Generated by Django 4.2.16 on 2024-09-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='tournament_id',
            field=models.IntegerField(default=0),
        ),
    ]
