# Generated by Django 5.1 on 2024-08-20 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='game_state',
        ),
    ]
