# Generated by Django 5.1 on 2024-08-26 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="is_tournament",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="TournamentSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "game1",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="game1",
                        to="game.gamesession",
                    ),
                ),
                (
                    "game2",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="game2",
                        to="game.gamesession",
                    ),
                ),
                (
                    "game3",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="game3",
                        to="game.gamesession",
                    ),
                ),
                (
                    "player1",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tournament1",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player2",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tournament2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player3",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tournament3",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player4",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tournament4",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
