# Generated by Django 5.1 on 2024-08-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_gamesession_is_tournament_tournamentsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentsession",
            name="code",
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
