# Generated by Django 5.1 on 2024-08-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_tournamentsession_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournamentsession",
            name="code",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
