# Generated by Django 5.1 on 2024-08-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_gamesession_rank_change1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamesession',
            old_name='rank_change',
            new_name='rank_change1',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='rank_change2',
            field=models.IntegerField(default=0),
        ),
    ]
