# Generated by Django 5.1 on 2024-08-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_alter_tournamentsession_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentsession",
            name="name",
            field=models.CharField(max_length=40, null=True),
        ),
    ]
