# Generated by Django 5.1 on 2024-08-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_tournamentsession_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="connected",
            field=models.BooleanField(default=False),
        ),
    ]
