FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y wget unzip && \
    wget https://bin.equinox.io/c/4b5I6e8d0Zy/ngrok-stable-linux-amd64.zip && \
    unzip ngrok-stable-linux-amd64.zip && \
    mv ngrok /usr/local/bin/

COPY fetch_and_run_ngrok.sh /fetch_and_run_ngrok.sh
RUN chmod +x /fetch_and_run_ngrok.sh
ENTRYPOINT ["/fetch_and_run_ngrok.sh"]
