FROM hashicorp/vault:1.17.3

COPY vault-entrypoint.sh /vault/scripts/vault-entrypoint.sh

RUN mkdir -p /vault/file/ && chmod 777 /vault/file
RUN mkdir -p /vault/token-volume/ && chmod 777 /vault/token-volume/

RUN chmod +x /vault/scripts/vault-entrypoint.sh
EXPOSE 8200

ENTRYPOINT ["/vault/scripts/vault-entrypoint.sh"]