# Generated by Django 4.2.15 on 2024-08-28 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_onetimepassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimepassword',
            name='email',
            field=models.EmailField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='onetimepassword',
            name='times',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='token_reset_password',
            field=models.CharField(default='', max_length=100, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='twoFaEnable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='onetimepassword',
            name='code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.CreateModel(
            name='OneTimePasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=255, unique=True)),
                ('reset_token', models.CharField(default='', max_length=200)),
                ('times', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OneTimePasswordLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=255, unique=True)),
                ('code', models.CharField(default='', max_length=10)),
                ('times', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
